openapi: 3.0.0
info:
  title: KUSHOP API
  description: KUSHOP Project from Kasetsart University Sriracha Campus.
  version: 0.1
servers:
  - url: http://localhost:3000/
    # description: My Localhost
paths:
  /products:
    # GET All Product
    get:
      summary: Returns a list all of products.
      # สามารถอธิบายรายละเอียดได้
      # เครื่องหมาย |
      description: |
        List all products in array of object format.<br>
        Each product contains details like product ID, name, price, etc.
      # ส่วนอธิบายว่าจะส่ง Status Cose อะไรกลับไปบ้าง
      responses:
        '200':    # status code
          description: A JSON array of Products
          content:
            application/json:
              schema:
                type: array
                items:
                  # อ้างอิงไปที่ Component เพื่อแสดงรายละเอียด
                  $ref: '#/components/schemas/products'  
# กำหนด Component ที่ต้องการแสดงรายละเอียด
components:
  schemas:
    products:
      type: object
      properties:
        pdId:
          type: string
        pdName:
          type: string
        pdPrice:
          # integer , number
          type: number
        pdRemark:
          type: string
        pdTypeId:
          type: string
        brandId:
          type: string
        brand:
          $ref: '#/components/schemas/brands'
        pdt:
          $ref: '#/components/schemas/productType'
    brands:
      type: object
      properties:
        brandId:
          type: string
        brandName:
          type: string 
    productType:
      type: object
      properties:
        pdTypeId:
          type: string
        pdTypeName:
          type: string
